import { ReactNode } from "react";

import cl from "clsx";
import type { Metadata } from "next";

import { doto } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const bodyClass = cl(doto.className, "antialiased w-full h-full bg-slate-300");
  return (
    <html lang="en" className={"w-full h-full"}>
      <body className={bodyClass}>
        <main className={"w-full h-full"}>{children}</main>
      </body>
    </html>
  );
}
