export const models = {
  avatarModelUrl: "/models/avatar/avatar.glb",
  avatarIdlelUrl: "/models/avatar/idle.fbx",
  avatarWalkinglUrl: "/models/avatar/walking.fbx",
  avatarHelllolUrl: "/models/avatar/hello.fbx",
  tesseractUrl: "/models/tesseract/scene.gltf",
  nintendoUrl: "/models/nintendo/scene.gltf",
  diskUrl: "/models/floppy_disk/scene.gltf",
  makUrl: "/models/mac-draco.glb",
  reactUrl: "/models/react_logo/scene.gltf",
  htmlUrl: "/models/html5_logo/scene.gltf",
  jsUrl: "/models/javascript_logo/scene.gltf",
  gamingUrl: "/models/gaming/scene.gltf",
  videoUrl: `https://firebasestorage.googleapis.com/v0/b/yodi-b787d.appspot.com/o/videoplayback.mp4?alt=media&token=${process.env.NEXT_PUBLIC_TOKEN}`,
};
